name: Deploy Azure MLZ

on:
  push:
    branches:
      - main  # This workflow will run whenever there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This job will run on the latest version of Ubuntu
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # This step checks out your repository's code onto the runner

    - name: Azure CLI script
      run: |
        az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} 
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az group create --name mlzResourceGroup --location eastus
        az deployment group create --resource-group mlzResourceGroup --template-uri https://raw.githubusercontent.com/Azure/missionlz/main/src/bicep/main.bicep
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
