name: Deploy Azure MLZ

on:
  push:
    branches:
      - main  # This workflow will run whenever there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This job will run on the latest version of Ubuntu
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This step checks out your repository's code onto the runner

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'  # This step logs into Azure using the Azure CLI

    - name: Azure CLI script
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # This command sets the active subscription
        az group create --name mlzResourceGroup --location eastus  # This command creates a resource group
        az deployment group create --resource-group mlzResourceGroup --template-uri https://raw.githubusercontent.com/Azure/missionlz/main/src/bicep/main.bicep  # This command deploys the Azure MLZ
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # These are environment variables for the Azure CLI script
